######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 3 09:39:21 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += processimage.h
SOURCES += main.cpp processimage.cpp
