######################################################################
# Automatically generated by qmake (3.0) ?? 3? 14 16:08:59 2014
######################################################################

TEMPLATE = app
TARGET = PostProcess
INCLUDEPATH += .

# Input
HEADERS += processimage.h
SOURCES += main.cpp processimage.cpp
